version: '3.3'
services:
  webapp:
    image: jdelivuk/docker-java-practical:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 32M
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - celsius
    links:
      - "db:dev-database"
  db:
    image: mysql:5.6 
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: conductor
    networks:
      - celsius
networks:
  celsius:
      driver: bridge
volumes:
    db_data:
